---
- hosts: dev
  become: yes
  tasks:
  - name: This task to install webserver
    yum:
     name: httpd
     state: latest
  - name: start webserver service
    service:
     name: httpd
     state: started 
  - name: copy index.html file to target
    copy:
     src: index.html
     dest: /var/www/html