pipeline {
    agent any
    tools {
        terraform 'Terraform v1.3.5' 
    }
    stages {
        stage('Install Terraform') {
            steps {
                sh 'sudo yum install wget -auto--approve'
            }
            steps {
                sh 'sudo wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg'
            }
            steps {
                sh 'echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list'
            }
            steps {
                sh 'sudo apt update && sudo apt install terraform -auto--approve'
            }
        }
    }
}